# -*- coding: utf-8 -*-
"""DL_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKq6vme3kh8L-6V2wGemZQYv5a6SFGDo
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/

# Commented out IPython magic to ensure Python compatibility.
!mkdir RAVDESS
# %cd RAVDESS

import os

base_url = "https://zenodo.org/records/1188976/files/"

for i in range(1, 25):
    actor = str(i).zfill(2)
    file_name = f"Video_Speech_Actor_{actor}.zip"
    url = base_url + file_name

    print(f"Downloading {file_name}...")
    os.system(f'wget --content-disposition "{url}"')

import zipfile
import os

for file in os.listdir():
    if file.endswith(".zip"):
        print(f"Extracting {file}...")
        with zipfile.ZipFile(file, 'r') as zip_ref:
            zip_ref.extractall()

!rm *.zip

# Install once per session
!pip install -q librosa moviepy mtcnn

from google.colab import drive
drive.mount('/content/drive')

import os

DATA_PATH = "/content/drive/MyDrive/RAVDESS/"   # your extracted dataset
SAVE_PATH = "/content/drive/MyDrive/RAVDESS_processed/"

FRAMES_PATH = os.path.join(SAVE_PATH, "frames")
AUDIO_PATH  = os.path.join(SAVE_PATH, "audio")
LABEL_PATH  = os.path.join(SAVE_PATH, "labels.npy")

os.makedirs(FRAMES_PATH, exist_ok=True)
os.makedirs(AUDIO_PATH, exist_ok=True)

def get_emotion_label(file_path):
    filename = os.path.basename(file_path)
    emotion_code = filename.split("-")[2]

    # Reduced classes (recommended)
    emotion_map = {
        "01": 0,  # neutral
        "02": 0,  # calm → merge into neutral
        "03": 1,  # happy
        "04": 2,  # sad
        "05": 3,  # angry
        "06": 4   # fear
    }

    return emotion_map.get(emotion_code, -1)

import cv2
from mtcnn import MTCNN

detector = MTCNN()

def extract_face_frames(video_path, frame_skip=5, max_frames=20):
    cap = cv2.VideoCapture(video_path)
    frames = []
    count = 0

    while len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret:
            break

        if count % frame_skip == 0:
            rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            faces = detector.detect_faces(rgb)

            if faces:
                x, y, w, h = faces[0]['box']
                x, y = max(0, x), max(0, y)
                face = rgb[y:y+h, x:x+w]
                face = cv2.resize(face, (112, 112))
                frames.append(face)

        count += 1

    cap.release()

    # Padding (important for batching)
    while len(frames) < max_frames:
        frames.append(frames[-1] if frames else np.zeros((112,112,3)))

    return frames

import librosa
import numpy as np

def extract_mfcc(video_path, max_len=100):
    try:
        audio, sr = librosa.load(video_path, sr=22050)
        mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)

        # Normalize length
        if mfcc.shape[1] < max_len:
            pad_width = max_len - mfcc.shape[1]
            mfcc = np.pad(mfcc, ((0,0),(0,pad_width)), mode='constant')
        else:
            mfcc = mfcc[:, :max_len]

        return mfcc

    except Exception as e:
        print("Audio error:", video_path)
        return np.zeros((40, max_len))

video_files = []

for root, dirs, files in os.walk(DATA_PATH):
    for file in files:
        if file.endswith(".mp4"):
            video_files.append(os.path.join(root, file))

print("Total videos:", len(video_files))

labels_dict = {}

# Load existing labels if present
if os.path.exists(LABEL_PATH):
    labels_dict = np.load(LABEL_PATH, allow_pickle=True).item()

for idx, video in enumerate(video_files):
    video_id = os.path.basename(video).replace(".mp4", "")

    frame_file = os.path.join(FRAMES_PATH, video_id + ".npy")
    audio_file = os.path.join(AUDIO_PATH, video_id + ".npy")

    # ✅ Skip already processed
    if os.path.exists(frame_file) and os.path.exists(audio_file):
        continue

    try:
        frames = extract_face_frames(video)
        mfcc   = extract_mfcc(video)
        label  = get_emotion_label(video)

        if label == -1:
            continue

        np.save(frame_file, np.array(frames, dtype=np.uint8))
        np.save(audio_file, mfcc.astype(np.float32))

        labels_dict[video_id] = label

        # Save labels after each step (important)
        np.save(LABEL_PATH, labels_dict)

        print(f"[{idx+1}/{len(video_files)}] Saved:", video_id)

    except Exception as e:
        print("Error processing:", video)

